# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1651e24433fc5ce75adc1f3a97022074cb74a22ce19be9a60eebc53eec8ffe85fee519ef7decad8ce63f3f9be7d2f211c70c23777c025f7b5500eae6237b7252

test:
  secret_key_base: fec026c89cb5e6993852f2c4899370e4ff5f7c4f10e5c0ab91f69496de20636713b574aa66f4093628312c63ae794c9778186fdc7935affd015839d89910ba9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
